CREATE SCHEMA IF NOT EXISTS `exaFinal` DEFAULT CHARACTER SET utf8 ;
USE `exaFinal`;

CREATE TABLE IF NOT EXISTS `sede_polideportivo` (
  `ID_SEDE` int(11) NOT NULL,
  `NOMBRE_SEDE` varchar(100) DEFAULT NULL,
  `CAPACIDAD` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_SEDE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tipo_deporte` (
  `ID_TIPO_DEPORTE` int(11) NOT NULL,
  `NOMBRE_DEPORTE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_DEPORTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `estado_partido` (
  `ID_ESTADO` int(11) NOT NULL,
  `NOMBRE_ESTADO` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tbl_tipousuario` (
  `tipuid` INT NOT NULL AUTO_INCREMENT,
  `tipunombre` VARCHAR(60) NOT NULL,
  `tipuestatus` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`tipuid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tbl_usuario` (
  `usuid` INT NOT NULL AUTO_INCREMENT,
  `usunombre` VARCHAR(45) NOT NULL,
  `usucontrasena` VARCHAR(25) NOT NULL,
  `usuultimasesion` DATE,
  `usuestatus` VARCHAR(1) NOT NULL,
  `usunombrereal` VARCHAR(60),
  `usucorreoe` VARCHAR(60),
  `usutelefono` VARCHAR(25),
  `usudireccion` VARCHAR(80),
  `tipuid` INT NOT NULL,
  PRIMARY KEY (`usuid`),
  FOREIGN KEY (`tipuid`) REFERENCES `tbl_tipousuario` (`tipuid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tbl_aplicacion` (
  `aplid` INT NOT NULL AUTO_INCREMENT,
  `aplnombre` VARCHAR(50),
  `aplestatus` VARCHAR(50),
  PRIMARY KEY (`aplid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tbl_bitacora` (
  `bitid` INT AUTO_INCREMENT PRIMARY KEY,
  `bitfecha` DATETIME NULL,
  `bitaccion` VARCHAR(10) NOT NULL,
  `bitip` VARCHAR(25) NOT NULL,
  `usuid` INT NOT NULL,
  `aplid` INT NOT NULL,
  `bitnombrepc` VARCHAR(50) NOT NULL,
  FOREIGN KEY (`aplid`) REFERENCES `tbl_aplicacion` (`aplid`),
  FOREIGN KEY (`usuid`) REFERENCES `tbl_usuario` (`usuid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tipo_puesto` (
  `ID_TIPO_PUESTO` int(11) NOT NULL,
  `NOMBRE_PUESTO` varchar(60) DEFAULT NULL,
  `SALARIO` double DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_PUESTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `empleado` (
  `ID_EMPLEADO` int(11) NOT NULL,
  `NOMBRE1` varchar(45) DEFAULT NULL,
  `NOMBRE2` varchar(45) DEFAULT NULL,
  `APELLIDO1` varchar(45) DEFAULT NULL,
  `APELLIDO2` varchar(45) DEFAULT NULL,
  `CORREO` varchar(60) DEFAULT NULL,
  `ID_TIPO_PUESTO` int(11) NOT NULL,
  `DIRECCION` varchar(100) DEFAULT NULL,
  `FECHA_NACIMIENTO` date DEFAULT NULL,
  `NIT` varchar(30) DEFAULT NULL,
  `DPI` varchar(20) DEFAULT NULL,
  `ID_USUARIO_FK` int(5) NOT NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  FOREIGN KEY (`ID_USUARIO_FK`) REFERENCES `tbl_usuario` (`usuid`),
  FOREIGN KEY (`ID_TIPO_PUESTO`) REFERENCES `tipo_puesto` (`ID_TIPO_PUESTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `telefono` (
  `ID_TELEFONO` int(11) NOT NULL,
  `ID_EMPLEADO_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID_TELEFONO`),
  FOREIGN KEY (`ID_EMPLEADO_FK`) REFERENCES `empleado` (`ID_EMPLEADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tipo_puesto` (
  `ID_TIPO_PUESTO` int(11) NOT NULL,
  `NOMBRE_PUESTO` varchar(60) DEFAULT NULL,
  `SALARIO` double DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_PUESTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `entrenador` (
  `ID_ENTRENADOR` int(11) NOT NULL,
  `NOMBRE1` varchar(45) DEFAULT NULL,
  `NOMBRE2` varchar(45) DEFAULT NULL,
  `APELLIDO1` varchar(45) DEFAULT NULL,
  `APELLIDO2` varchar(45) DEFAULT NULL,
  `FECHA_NACIMIENTO` date DEFAULT NULL,
  `ID_USUARIO_FK` INT(5) NOT NULL,
  PRIMARY KEY (`ID_ENTRENADOR`),
  FOREIGN KEY (`ID_USUARIO_FK`) REFERENCES `tbl_usuario` (`usuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `equipo` (
  `ID_EQUIPO` int(11) NOT NULL,
  `NOMBRE_EQUIPO` varchar(50) DEFAULT NULL,
  `ID_ENTRENADOR_FK` int(11) NOT NULL,
  `ID_TIPO_DEPORTE__FK` int(11) NOT NULL,
  `TORNEOS_GANADOS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_EQUIPO`),
  FOREIGN KEY (`ID_ENTRENADOR_FK`) REFERENCES `entrenador` (`ID_ENTRENADOR`),
  FOREIGN KEY (`ID_TIPO_DEPORTE__FK`) REFERENCES `tipo_deporte` (`ID_TIPO_DEPORTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `jugador` (
  `ID_JUGADOR` int(11) NOT NULL,
  `NOMBRE1` varchar(45) DEFAULT NULL,
  `NOMBRE2` varchar(45) DEFAULT NULL,
  `APELLIDO1` varchar(45) DEFAULT NULL,
  `APELLIDO2` varchar(45) DEFAULT NULL,
  `FECHA_NACIMIENTO` date DEFAULT NULL,
  `ID_EQUIPO_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_JUGADOR`),
  FOREIGN KEY (`ID_EQUIPO_FK`) REFERENCES `equipo` (`ID_EQUIPO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `campeonato` (
  `ID_CAMPEONATO` int(11) NOT NULL,
  `NOMBRE_CAMPEONATO` varchar(60) DEFAULT NULL,
  `CANTIDAD_EQUIPOS` int(11) DEFAULT NULL,
  `ID_SEDE_POLI_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID_CAMPEONATO`),
  FOREIGN KEY (`ID_SEDE_POLI_FK`) REFERENCES `sede_polideportivo` (`ID_SEDE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `detalle_partido` (
  `ID_PARTIDO` int(11) NOT NULL,
  `ID_CAMPEONATO_FK` int(11) NOT NULL,
  `FECHA_PARTIDO` datetime DEFAULT NULL,
  `ID_LOCAL` int(11) NOT NULL,
  `ID_VISITANTE` int(11) NOT NULL,
  `MARCADOR` varchar(9) DEFAULT NULL,
  `ID_MEJOR_JUGADOR_FK` int(11) NOT NULL,
  `FALTAS` varchar(45) DEFAULT NULL,
  `ID_ESTADO_PARTIDO_FK` int(11) NOT NULL,
  PRIMARY KEY (`ID_PARTIDO`),
  FOREIGN KEY (`ID_CAMPEONATO_FK`) REFERENCES `campeonato` (`ID_CAMPEONATO`),
  FOREIGN KEY (`ID_LOCAL`) REFERENCES `equipo` (`ID_EQUIPO`),
  FOREIGN KEY (`ID_VISITANTE`) REFERENCES `equipo` (`ID_EQUIPO`),
  FOREIGN KEY (`ID_MEJOR_JUGADOR_FK`) REFERENCES `jugador` (`ID_JUGADOR`),
  FOREIGN KEY (`ID_ESTADO_PARTIDO_FK`) REFERENCES `estado_partido` (`ID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `estado_partido` (
  `ID_ESTADO` int(11) NOT NULL,
  `NOMBRE_ESTADO` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sede_polideportivo` (
  `ID_SEDE` int(11) NOT NULL,
  `NOMBRE_SEDE` varchar(100) DEFAULT NULL,
  `CAPACIDAD` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_SEDE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tipo_deporte` (
  `ID_TIPO_DEPORTE` int(11) NOT NULL,
  `NOMBRE_DEPORTE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_DEPORTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tbl_tipousuario` (
  `tipuid` INT NOT NULL AUTO_INCREMENT,
  `tipunombre` VARCHAR(60) NOT NULL,
  `tipuestatus` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`tipuid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tbl_usuario` (
  `usuid` INT NOT NULL AUTO_INCREMENT,
  `usunombre` VARCHAR(45) NOT NULL,
  `usucontrasena` VARCHAR(25) NOT NULL,
  `usuultimasesion` DATE,
  `usuestatus` VARCHAR(1) NOT NULL,
  `usunombrereal` VARCHAR(60),
  `usucorreoe` VARCHAR(60),
  `usutelefono` VARCHAR(25),
  `usudireccion` VARCHAR(80),
  `tipuid` INT NOT NULL,
  PRIMARY KEY (`usuid`),
  FOREIGN KEY (`tipuid`) REFERENCES `tbl_tipousuario` (`tipuid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tbl_aplicacion` (
  `aplid` INT NOT NULL AUTO_INCREMENT,
  `aplnombre` VARCHAR(50),
  `aplestatus` VARCHAR(50),
  PRIMARY KEY (`aplid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tbl_bitacora` (
  `bitid` INT AUTO_INCREMENT PRIMARY KEY,
  `bitfecha` DATETIME NULL,
  `bitaccion` VARCHAR(10) NOT NULL,
  `bitip` VARCHAR(25) NOT NULL,
  `usuid` INT NOT NULL,
  `aplid` INT NOT NULL,
  `bitnombrepc` VARCHAR(50) NOT NULL,
  FOREIGN KEY (`aplid`) REFERENCES `tbl_aplicacion` (`aplid`),
  FOREIGN KEY (`usuid`) REFERENCES `tbl_usuario` (`usuid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;